---
title: "Introdução A Python"
toc: true
toc-title: "Conteúdos da página"
---

[Apresentação de slides do tema](slides/slides-variaveis.pdf)

## Variáveis em python

Em Python, as variáveis representam espaços na memória utilizados para armazenar dados que podem ser manipulados durante a execução de um programa. Esses dados podem ser de diferentes tipos, como números (`int` e `float`), textos (`string`), listas (`list`), dicionários (`dict`) ou até objetos mais complexos (cenas dos próximos capítulos). Uma das principais características da linguagem é sua tipagem dinâmica, o que significa que não é necessário declarar previamente o tipo de uma variável — o interpretador identifica automaticamente o tipo de dado com base no valor atribuído a ela. Assim, uma variável pode receber um número em um momento e, posteriormente, um texto, sem que o programador precise realizar uma redefinição explícita do tipo.

Declarar uma variável, em termos conceituais, significa criar uma referência que aponta para um determinado valor armazenado na memória. Já inicializar uma variável consiste em atribuir-lhe um valor inicial, permitindo que o programa utilize essa informação. Em Python, a declaração e a inicialização geralmente ocorrem simultaneamente, pois basta atribuir um valor a um nome para que a variável seja criada.

Apesar da flexibilidade proporcionada pela tipagem dinâmica, o Python também oferece a possibilidade de indicar explicitamente o tipo esperado de uma variável por meio das chamadas type hints. Esses indicadores não alteram o funcionamento do código em tempo de execução, mas servem como uma forma de documentação e auxiliam ferramentas de análise estática, tornando o código mais legível, seguro e fácil de manter. Essa prática é especialmente útil em projetos de maior porte, nos quais a clareza sobre o tipo de dados esperados em cada parte do programa contribui para reduzir erros e melhorar a colaboração entre desenvolvedores.

### Declaração de variáveis

Em Python, declarar uma variável é muito simples: basta escolher um nome e atribuir um valor a ele usando o sinal de igual (`=`), o operador de atribuição do Python. A linguagem cria automaticamente a variável e identifica seu tipo com base no valor atribuído. Não é necessário especificar o tipo antes, pois o Python faz isso automaticamente.

O padrão de declaração, portanto é:

```{python}
#| eval: false
nome_da_variavel: tipo_da_variavel = valor_da_variavel
```

ou (sem especificação do tipo da variável)

```{python}
#| eval: false
nome_da_variavel = valor_da_variavel
```

A seguir estão os principais tipos de variáveis que você pode declarar:

### Inteiros (`int`):

Para declarar um `int` chamado "variavel_tipo_inteiro" inicializado com o valor 5, basta fazer o seguinte:

```{python}
#| eval: false
variavel_tipo_inteiro: int = 5
```

ou

```{python}
#| eval: false
variavel_tipo_inteiro = 5
```

### Ponto flutuante (`float`): 

Para declarar um `float` chamado "variavel_tipo_float" incializado com o valor 3.14, basta fazer o seguinte:

```{python}
#| eval: false
variavel_tipo_float: float = 3.14
```

ou

```{python}
#| eval: false
variavel_tipo_float = 3.14
```

### Texto (`str`):

Para declarar uma `string` chamada "variavel_tipo_string" incializada com o valor "Minha string", basta fazer o seguinte:

```{python}
#| eval: false
variavel_tipo_string: str = "Minha string"
```

ou

```{python}
#| eval: false
variavel_tipo_string = "Minha string"
```

::: {.callout-note title="Observação importante"}

O tipo `string` em Python é chamado `str`, e, para incializá-lo com algum valor, este valor pode estar em aspas duplas ("") ou aspas simples. Assim, aqui estão outras duas maneiras de declarar as mesmas variáveis:

```{python}
#| eval: false
variavel_tipo_string: str = 'Minha string'
```

ou

```{python}
#| eval: false
variavel_tipo_string = 'Minha string'
```

:::

### Booleanos (`bool`):

Para declarar um `bool` chamado "variavel_tipo_bool" incializado com o valor True, basta fazer o seguinte:

```{python}
#| eval: false
variavel_tipo_bool: bool = True
```

ou

```{python}
#| eval: false
variavel_tipo_bool = True
```

### Listas (`list`): 

Para declarar um `list` chamada "variavel_tipo_lista" e incializá-lo com algum(s) valor(es), basta fazer o seguinte:

```{python}
#| eval: false
variavel_tipo_lista: list = [1, 4, 89]
```

ou

```{python}
#| eval: false
variavel_tipo_lista = [1, 4, 89]
```

::: {.callout-note title="Observação importante"}

Uma lista pode conter conter qualquer tipo de variável nos seus elementos, poranto todas as listas seguintes são listas válidas em python:

```{python}
#| eval: false
variavel_tipo_lista: list = [1, 2, 3]
```

```{python}
#| eval: false
variavel_tipo_lista: list = ['a', 'b', 'c']
```

```{python}
#| eval: false
variavel_tipo_lista: list = [True, False, True]
```

Portanto, como uma lista pode conter qualquer tipo de variável em seus elementos, isto nos leva a dois casos "extremos" que são completamente válidos em python (e quase toda lingugagem de programção):

1. Lista vazia, delcarada a seguir:


```{python}
#| eval: false
variavel_tipo_lista: list = []
```


2. Lista de listas, declarada a seguir:


```{python}
#| eval: false
variavel_tipo_lista: list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
```

Estas listas de listas são a base de estruturas chamadas [matrizes](https://www.geeksforgeeks.org/dsa/introduction-to-matrix-or-grid-data-structure-and-algorithms-tutorial/), que serão estudas posteriormente.

:::

### Dicionários (`dict`)

  Para declarar um `dict` chamado "variavel_tipo_dict" e incializá-lo com algumas chaves e valores, basta fazer o seguinte:


  ```{python}
  #| eval: false
  variavel_tipo_dict: dict = {'chave_1' : 1, 'chave_2' : 2, 'chave_3' : 3}
  ```

  ou


  ```{python}
  #| eval: false
  variavel_tipo_dict = {'chave_1' : 1, 'chave_2' : 2, 'chave_3' : 3}
  ```

### Outros tipos

Existem ainda outros tipos de variáveis em python, com destaque o [`tuple`](https://www.w3schools.com/python/python_tuples.asp) e o [`set`](https://www.w3schools.com/python/python_sets.asp), mas ester tipos serão estudados posteriormente.

## Operadores por tipo de variável

Em Python, cada tipo de variável possui um conjunto de operadores que podem ser utilizados com ele. Os operadores são símbolos ou palavras especiais que indicam ao interpretador que deve realizar uma operação sobre um ou mais valores. A seguir, apresentamos os principais tipos de variáveis e seus operadores, explicando o funcionamento de cada um.

### Tipo Inteiro (`int`)

| Operador | Nome | Descrição | Exemplo | Resultado |
|-----------|------|------------|----------|------------|
| `+` | Adição | Soma dois valores inteiros | `3 + 2` | `5` |
| `-` | Subtração | Subtrai o segundo número do primeiro | `5 - 3` | `2` |
| `*` | Multiplicação | Multiplica dois números inteiros | `4 * 3` | `12` |
| `/` | Divisão | Divide o primeiro número pelo segundo (resultado `float`) | `7 / 2` | `3.5` |
| `//` | Divisão inteira | Retorna apenas a parte inteira da divisão | `7 // 2` | `3` |
| `%` | Módulo | Retorna o resto da divisão inteira | `7 % 2` | `1` |
| `**` | Exponenciação | Eleva o primeiro número à potência do segundo | `2 ** 3` | `8` |
| `==` | Igualdade | Verifica se dois valores são iguais | `3 == 3` | `True` |
| `!=` | Diferente | Verifica se dois valores são diferentes | `3 != 2` | `True` |
| `>` | Maior que | Retorna `True` se o primeiro for maior | `5 > 2` | `True` |
| `<` | Menor que | Retorna `True` se o primeiro for menor | `2 < 5` | `True` |
| `>=` | Maior ou igual | Verifica se é maior ou igual | `4 >= 4` | `True` |
| `<=` | Menor ou igual | Verifica se é menor ou igual | `3 <= 5` | `True` |
| `+=` | Atribuição com soma | Soma e atribui o resultado | `a = 5; a += 2` | `a = 7` |
| `-=` | Atribuição com subtração | Subtrai e reatribui o resultado | `a = 5; a -= 2` | `a = 3` |

<br><br>

### Tipo Ponto Flutuante (`float`)

| Operador | Nome | Descrição | Exemplo | Resultado |
|-----------|------|------------|----------|------------|
| `+` | Adição | Soma dois valores | `3.2 + 2.7` | `5.9` |
| `-` | Subtração | Subtrai o segundo número do primeiro | `5.0 - 3.1` | `1.9` |
| `*` | Multiplicação | Multiplica dois números | `4.2 * 2.0` | `8.4` |
| `/` | Divisão | Divide o primeiro número pelo segundo (resultado `float`) | `7.0 / 2.0` | `3.5` |
| `//` | Divisão inteira | Retorna apenas a parte inteira da divisão (como um `float`) | `7.0 // 2.0` | `3.0` |
| `%` | Módulo | Retorna o resto da divisão inteira | `7.25 % 3.5` | `0.25` |
| `**` | Exponenciação | Eleva o primeiro número à potência do segundo | `2.0 ** 3.0` | `8.0` |
| `==` | Igualdade | Verifica se dois valores são iguais | `3.14 == 3.14` | `True` |
| `!=` | Diferente | Verifica se dois valores são diferentes | `7.34 != 5.67` | `True` |
| `>` | Maior que | Retorna `True` se o primeiro for maior | `3.1 > 3` | `True` |
| `<` | Menor que | Retorna `True` se o primeiro for menor | `3.0 < 8.6` | `True` |
| `>=` | Maior ou igual | Verifica se é maior ou igual | `3.14 >= 3.14` | `True` |
| `<=` | Menor ou igual | Verifica se é menor ou igual | `2.7 <= 5.0` | `True` |
| `+=` | Atribuição com soma | Soma e atribui o resultado | `a = 5.0; a += 2.2` | `a = 7.2` |
| `-=` | Atribuição com subtração | Subtrai e reatribui o resultado | `a = 3.5; a -= 2.0` | `a = 1.5` |

<br><br>

### Tipo String (`str`)

| Operador | Nome | Descrição | Exemplo | Resultado |
|-----------|------|------------|----------|------------|
| `+` | Concatenação | Junta duas strings | `"Olá, " + "mundo!"` | `"Olá, mundo!"` |
| `*` | Repetição | Repete uma string N vezes | `"Oi" * 3` | `"OiOiOi"` |
| `==` | Igualdade | Verifica se duas strings são idênticas | `"abc" == "abc"` | `True` |
| `!=` | Diferente | Verifica se são diferentes | `"a" != "b"` | `True` |
| `<` | Comparação lexicográfica | Compara pela ordem alfabética | `"a" < "b"` | `True` |
| `>` | Comparação lexicográfica | Compara pela ordem alfabética | `"b" > "a"` | `True` |
| `<=` | Comparação lexicográfica | Compara pela ordem alfabética | `"a" <= "a"` | `True` |
| `>=` | Comparação lexicográfica | Compara pela ordem alfabética | `"b" >= "b"` | `True` |
| `in` | Contém | Verifica se uma substring existe | `"Py" in "Python"` | `True` |
| `not in` | Não contém | Verifica se uma substring não existe | `"java" not in "python"` | `True` |
| `[ ]` | Acesso por índice | Acessa um caractere da string | `"Python"[0]` | `"P"` |

<br><br>

### Tipo Booleano (`bool`)

| Operador | Nome | Descrição | Exemplo | Resultado |
|-----------|------|------------|----------|------------|
| `and` | E lógico | Verdadeiro se **ambos** forem verdadeiros | `True and False` | `False` |
| `or` | OU lógico | Verdadeiro se **um** for verdadeiro | `True or False` | `True` |
| `not` | Negação | Inverte o valor lógico | `not True` | `False` |
| `==` | Comparação | Compara se dois valores booleanos sã iguais | `True == False` | `False` |
| `!=` | Comparação | Compara se dois valores booleanos são diferentes | `True != False` | `True` |

<br><br>

### Tipo Lista (`list`)

| Operador | Nome | Descrição | Exemplo | Resultado |
|-----------|------|------------|----------|------------|
| `+` | Concatenação | Junta duas listas | `[1, 2] + [3, 4]` | `[1, 2, 3, 4]` |
| `*` | Repetição | Repete os elementos | `[1, 2] * 2` | `[1, 2, 1, 2]` |
| `in` | Contém | Verifica se um valor está na lista | `3 in [1, 2, 3]` | `True` |
| `not in` | Não contém | Verifica se um valor não está na lista | `5 not in [1, 2, 3]` | `True` |
| `[ ]` | Acesso por índice | Retorna o elemento em uma posição | `a = [10, 20, 30]; a[1]` | `20` |
| `==` | Comparação | Compara listas elemento a elemento, checando igualdade | `[1,2] == [1,2]` | `True` |
| `!=` | Comparação | Compara listas elemento a elemento, checando diferenças | `[1, 2] != [3, 4]` | `True` |

<br><br>

### Tipo Dicionário (`dict`)

| Operador | Nome | Descrição | Exemplo | Resultado |
|-----------|------|------------|----------|------------|
| `[ ]` | Acesso por chave | Retorna o valor associado | `d = {"a": 1}; d["a"]` | `1` |
| `in` | Verifica chave | Retorna `True` se a chave existir | `"a" in {"a": 1}` | `True` |
| `not in` | Verifica ausência | Retorna `True` se a chave não existir | `"b" not in {"a": 1}` | `True` |
| `==` | Comparação | Compara dicionários por conteúdo, checando igualdade | `{'a' : 1} == {'a' : 1}` | `True` |
| `!=` | Comparação | Comparada dicionários por conteúdo, checando diferenças | `{'a' : 1} != {'b' : 2}` | `True` |

<br><br>

### Observações gerais

Os operadores podem ter comportamentos diferentes dependendo do tipo de dado. Os exemplos mais importantes destas diferenças são os seguintes casos:

* `+` soma números, mas **concatena strings e listas**;

* `*` multiplica números, mas **repete strings e listas**;  

* `in` verifica **pertencimento** em strings, listas, tuplas, conjuntos e dicionários.

## Introdução básica a entradas e saídas de dados

Em Python, é comum precisarmos exibir informações na tela ou receber dados digitados pelo usuário.
Para isso, utilizamos as funções print() e input().

### Exibindo informações com print()

A função print() é usada para mostrar mensagens, resultados de operações ou valores de variáveis na tela.
Basta escrever o que você quer exibir entre parênteses e aspas.

```{python}
#| eval: false
print("Olá, mundo!")
```

::: {.callout-note title="Observação/Teste este código!"}

A saída do código acima é o texto "Olá, mundo!" impresso no terminal.

:::

Além de exibir texto escritos na função, é possível exibir o valor de variáveis utilizando a mesma lógica:

```{python}
#| eval: false
texto: str = "Olá, mundo!"
print(texto)
```

::: {.callout-note title="Observação/Teste este código!"}

A saída do código acima é o texto "Olá, mundo!" impresso no terminal.

:::

Também é possivel exibir mais de um texto, passando estes textos à função na ordem que você deseja que sejam mostrados, separados com vírgulas:

```{python}
#| eval: false
nome: str = "Maria"
print("Olá, ", nome)
```

::: {.callout-note title="Observação/Teste este código!"}

A saída do código acima é o texto "Olá, Maria" impresso no terminal.

:::

### Lendo informações com input()

A função input() serve para coletar dados digitados pelo usuário.
Tudo o que o usuário digitar será lido como uma `string` (`str`).

```{python}
#| eval: false
nome = input("Digite seu nome: ")
print("Olá, ", nome)
```

::: {.callout-note title="Observação/Teste este código!"}

Ao executar este código, será exibida a mensagem **"Digite seu nome:"** no terminal.  
O programa então aguardará que o usuário digite um valor e pressione **Enter**.  
O texto digitado será armazenado como uma `string` na variável `nome` e, em seguida, exibido na tela junto à saudação **"Olá, "**.

**Exemplo:**

Se o usuário digitar "Pedro", a saída será: "Olá, Pedro".

:::

Como toda coleta de dados realizada pela função input() é uma `string`, se for necessário trabalhar com números, é preciso converter o valor digitado usando int() ou float():

```{python}
#| eval: false
idade = int(input("Digite sua idade: "))
altura = float(input("Digite sua altura: "))
print("Você tem", idade, "anos e mede", altura, "metros.")
```

::: {.callout-note title="Observação/Teste este código!"}

Ao executar este código, o programa solicitará duas entradas do usuário:

1. **Idade**: será exibida a mensagem **"Digite sua idade:"** e o valor digitado será convertido para um número inteiro (`int`) e armazenado na variável `idade`.  
2. **Altura**: será exibida a mensagem **"Digite sua altura:"** e o valor digitado será convertido para um número decimal (`float`) e armazenado na variável `altura`.  

Após a coleta desses dados, o programa exibirá na tela a frase com os valores fornecidos:

**Exemplo:**

Se o usuário digitar `25` para a idade e `1.75` para a altura, a saída será: "Você tem 25 anos e mede 1.75 metros."

:::

### Tabela de consulta

| Função    | Utilidade                       | Tipo de dado retornado |
| --------- | ------------------------------- | ---------------------- |
| `print()` | Exibe informações na tela       | (Não retorna nada)     |
| `input()` | Lê dados digitados pelo usuário | `str` (texto)          |

## Comentários em Python

Comentários são partes do código que não são executadas pelo Python. Eles servem para explicar trechos do programa, deixar observações importantes ou facilitar o entendimento do código para outras pessoas — ou para você mesmo no futuro.

### Comentários de uma linha

Para criar um comentário de uma linha, utiliza-se o símbolo #.
Tudo o que estiver depois dele será ignorado pelo interpretador.

```{python}
#| eval: false
# Este é um comentário de uma linha

x: int = 10  # Também é possível comentar ao lado de um comando
```

### Comentários de múltiplas linhas

Python não possui um símbolo específico para comentários longos, mas é comum utilizar três aspas (simples ou duplas). Quando esse texto não é atribuído a nenhuma variável, ele é ignorado pelo interpretador e funciona como bloco de comentário.

#### Usando aspas duplas

```{python}
#| eval: false
"""
Este é um comentário
de múltiplas linhas.
Ele é útil para explicações mais longas.
"""
```

#### Usando aspas simples

```{python}
#| eval: false
'''
Também funciona com aspas simples.
Use quando quiser escrever textos longos.
'''
```

::: {.callout-note title="Observação importante"}

Apesar de serem usados como comentários longos, esses blocos também são considerados strings multilinha.
Eles só funcionam como comentário quando não são atribuídos a nenhuma variável.

:::

### Quando usar comentários?

Comentários são úteis quando:

* um trecho de código não é óbvio;

* é importante registrar o porquê de uma decisão;

* você quer facilitar a leitura para outras pessoas;

* deseja documentar partes específicas do algoritmo.

Evite escrever comentários desnecessários, como explicar algo óbvio demais. Prefira comentários que realmente esclareçam a intenção do código.

## Exercícios

### Exercício 1

Classifique as seguintes variáveis com base em seu tipo:

1. idade = 25

::: {.callout-tip collapse="true" title="Ver Solução"}

`int`, pois 25 é um número sem casas decimais.

:::

2. altura = 1.82

::: {.callout-tip collapse="true" title="Ver Solução"}

`float`, pois 1.82 é um número com casas decimais.

:::

3. nome = "Maria"

::: {.callout-tip collapse="true" title="Ver Solução"}

`str`, pois "Maria" é texto.

:::

4. aprovado = True

::: {.callout-tip collapse="true" title="Ver Solução"}

`bool`, pois True é um valor booleano.

:::

5. notas = [8.5, 7.0, 9.2]

::: {.callout-tip collapse="true" title="Ver Solução"}

`list`, pois a variável notas contém 3 posições, em cada uma delas sendo armazenado um `float`.

:::

6. dados = {"nome": "João", "idade": 20}

::: {.callout-tip collapse="true" title="Ver Solução"}

`dict`, pois a variável dados tem pares de chaves e valores.

:::

### Exercício 2

Assumindo que a é uma variável do tipo `int` com valor igual a 4 e b é uma variável do tipo `int` com valor igual a 2, complete a tabela:

| Operação | Resultado |
| -------- | --------- |
| a + b    |           |
| a - b    |           |
| a * b    |           |
| a / b    |           |
| a // b   |           |
| a % b    |           |
| a ** b   |           |

::: {.callout-tip collapse="true" title="Ver Solução"}

| Operação | Resultado |
| -------- | --------- |
| a + b    | 6         |
| a - b    | 2         |
| a * b    | 8         |
| a / b    | 2         |
| a // b   | 2         |
| a % b    | 0         |
| a ** b   | 16        |

:::

### Exercício 3

Analise o código a seguir e faça o que se pede:

```{python}
#| eval: false
a: str = '5'
b: str = '5'

c = a + b
```

1. Qual o valor da variável c?

::: {.callout-tip collapse="true" title="Ver Solução"}

Como a e b são duas variáveis do tipo `str`, para avaliar a soma das duas, basta entender que o operador `+` concatena (junta) duas variáveis do tipo `str`. Ou seja, o resultado será a concatenação de '5' com '5', que é igual a '55'.

:::

2. Qual o tipo da variável c?

::: {.callout-tip collapse="true" title="Ver Solução"}

Como a e b são duas  variáveis do tipo `str`, a concatenação de a e b resultará em uma outra variável do tpo `str`.

:::

### Exercício 4

Avalie o seguinte código:

```{python}
#| eval: false
a: int = 5

a += 2
a *= 2
a -= 4
```

Qual é o valor final da variável a?

::: {.callout-tip collapse="true" title="Ver Solução"}

Para descobrir o valor de a, basta realizar todas as operações que foram feitas em a.

1. a += 2 -> a = a + 2 -> a = 5 + 2 -> a = 7. Logo, após a execução da linha `a += 2`, o valor de a é 7.

2. a *= 2 -> a = a * 2 -> a = 7 * 2 -> a = 14. Logo, após a execução da linha `a *= 2`, o valor de a é 14.

3. a -= 4 -> a = a - 4 -> a = 14 - 4 -> a = 10. Logo, após a execução da linha `a -= 4`, o valor de a é 10.

Portanto, o valor final da variável a é 10.

:::

### Exercício 5

Dada a lista, faça o que se pede:

```{python}
#| eval: false
numeros = [10, 20, 30, 40]
```


1. O que significa numeros[2]?

::: {.callout-tip collapse="true" title="Ver Solução"}

numeros[2] significa acessar o elemento armazenado no índice 2 da lista numeros. Como a contagem de índices inicia em 0, numeros[2] nos retorna o terceiro elemento, neste caso 30.

:::

2. E numeros[0]?

::: {.callout-tip collapse="true" title="Ver Solução"}

numeros[0] significa acessar o primeiro elemento da lista numeros, que neste caso é 10.

:::

3. Como acessar o último elemento desta lista?

::: {.callout-tip collapse="true" title="Ver Solução"}

Para acessar o último elemento de uma lista com n elementos, basta acessar a lista na posição n - 1. Neste caso, n é 4, pois a lista possui 4 elementos, então, o comando para acessar o último elemento é numeros[3].

:::

## Desafio 

Dado o código:

```{python}
#| eval: false
aluno = {"nome": "Lucas", "notas": [7.5, 8.0, 9.0]}
media = (aluno["notas"][0] + aluno["notas"][1] + aluno["notas"][2]) / 3
```


1. O que o programa faz?

::: {.callout-tip collapse="true" title="Ver Solução"}

Este programa calcula a média de 3 notas: 7.5, 8.0 e 9.0, que estão armazenadas como uma lista, guardada dentro de um `dict`.

:::

2. O que significa aluno["notas"]?

::: {.callout-tip collapse="true" title="Ver Solução"}

Acessar aluno["notas"] significa acessar uma lista que está guardada na posição "notas" no `dict` aluno.

:::


3. Qual é o valor final da variável media?

::: {.callout-tip collapse="true" title="Ver Solução"}

O valor final é a soma de cada uma das posições de aluno["notas"] dividido por 3. Vamos descobrir estes valores passo a passo:

1. aluno["notas"][0] = 7.5

2. aluno["notas"][1] = 8.0

3. aluno["notas"][2] = 9.0

Logo, o cálculo é: $\frac{7.5 + 8.0 + 9.0}{3}$ -> $\frac{24.5}{3}$ -> $8.16666...$

Portanto, o valor final da variavel media é 8.166666

:::

4. Qual o tipo da variável media? 

::: {.callout-tip collapse="true" title="Ver Solução"}

A variável média é um float, pois o resultado da conta da média é um número com casas decimais.

:::